framework:
    messenger:
        transports:
            async: 'doctrine://default'
        routing:
            'App\Message\ProductDeleteMessage': async
            'App\Message\ProductUpdateMessage': async
